# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'BookShelf' do
  use_frameworks!

  pod 'Moya'
  pod 'Moya-ModelMapper'

  target 'BookShelfTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
